apiVersion: apps/v1
kind: Deployment
metadata:
  name: tz-py-crawler
spec:
  selector:
    matchLabels:
      app: tz-py-crawler
  replicas: 1
  template:
    metadata:
      labels:
        app: tz-py-crawler
    spec:
      containers:
      - name: tz-py-crawler
        image: doohee323/tz-py-crawler:5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
        volumeMounts:
          - name: nfs-persistent-storage
            mountPath: /mnt
      volumes:
        - name: nfs-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-nfs-dynamic

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-crawler
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: nfs-csi
